export const columns = [
   { name: "NAME", uid: "name" },
   { name: "AGE", uid: "age" },
   { name: "OVERALL", uid: "overall" },
   { name: "POTENTIAL", uid: "potential" },
   { name: "POSITION", uid: "position" },
   { name: "FLAG", uid: "flag" },
   { name: "ACTIONS", uid: "actions" },
 ];
export const users = [
  {
    id: 1,
    name: "Tony Reichert",
    role: "CEO",
    team: "Management",
    status: "active",
    age: "29",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026024d",
    email: "tony.reichert@example.com",
  },
  {
    id: 2,
    name: "Zoey Lang",
    role: "Technical Lead",
    team: "Development",
    status: "paused",
    age: "25",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026704d",
    email: "zoey.lang@example.com",
  },
  {
    id: 3,
    name: "Jane Fisher",
    role: "Senior Developer",
    team: "Development",
    status: "active",
    age: "22",
    avatar: "https://i.pravatar.cc/150?u=a04258114e29026702d",
    email: "jane.fisher@example.com",
  },
  {
    id: 4,
    name: "William Howard",
    role: "Community Manager",
    team: "Marketing",
    status: "vacation",
    age: "28",
    avatar: "https://i.pravatar.cc/150?u=a048581f4e29026701d",
    email: "william.howard@example.com",
  },
  {
    id: 5,
    name: "Kristen Copper",
    role: "Sales Manager",
    team: "Sales",
    status: "active",
    age: "24",
    avatar: "https://i.pravatar.cc/150?u=a092581d4ef9026700d",
    email: "kristen.cooper@example.com",
  },
  {
    id: 6,
    name: "Tony Reichert",
    role: "CEO",
    team: "Management",
    status: "active",
    age: "29",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026024d",
    email: "tony.reichert@example.com",
  },
  {
    id: 10,
    name: "Kristen Copper",
    role: "Sales Manager",
    team: "Sales",
    status: "active",
    age: "24",
    avatar: "https://i.pravatar.cc/150?u=a092581d4ef9026700d",
    email: "kristen.cooper@example.com",
  },
  {
    id: 8,
    name: "Jane Fisher",
    role: "Senior Developer",
    team: "Development",
    status: "active",
    age: "22",
    avatar: "https://i.pravatar.cc/150?u=a04258114e29026702d",
    email: "jane.fisher@example.com",
  },
  {
    id: 7,
    name: "Zoey Lang",
    role: "Technical Lead",
    team: "Development",
    status: "paused",
    age: "25",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026704d",
    email: "zoey.lang@example.com",
  },

  {
    id: 9,
    name: "William Howard",
    role: "Community Manager",
    team: "Marketing",
    status: "vacation",
    age: "28",
    avatar: "https://i.pravatar.cc/150?u=a048581f4e29026701d",
    email: "william.howard@example.com",
  },
  {
    id: 11,
    name: "Tony Reichert",
    role: "CEO",
    team: "Management",
    status: "active",
    age: "29",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026024d",
    email: "tony.reichert@example.com",
  },
  {
    id: 12,
    name: "Kristen Copper",
    role: "Sales Manager",
    team: "Sales",
    status: "active",
    age: "24",
    avatar: "https://i.pravatar.cc/150?u=a092581d4ef9026700d",
    email: "kristen.cooper@example.com",
  },
  {
    id: 13,
    name: "Jane Fisher",
    role: "Senior Developer",
    team: "Development",
    status: "active",
    age: "22",
    avatar: "https://i.pravatar.cc/150?u=a04258114e29026702d",
    email: "jane.fisher@example.com",
  },
  {
    id: 14,
    name: "Zoey Lang",
    role: "Technical Lead",
    team: "Development",
    status: "paused",
    age: "25",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026704d",
    email: "zoey.lang@example.com",
  },
  {
    id: 15,
    name: "Tony Reichert",
    role: "CEO",
    team: "Management",
    status: "active",
    age: "29",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026024d",
    email: "tony.reichert@example.com",
  },
  {
    id: 16,
    name: "Kristen Copper",
    role: "Sales Manager",
    team: "Sales",
    status: "active",
    age: "24",
    avatar: "https://i.pravatar.cc/150?u=a092581d4ef9026700d",
    email: "kristen.cooper@example.com",
  },
];

export const players = [
  {
    id: "1",
    name: "Lionel Messi",
    age: "34",
    photo: "https://i.pravatar.cc/150?u=lionel-messi",
    nationality: "Argentina",
    flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Flag_of_Argentina.svg/1280px-Flag_of_Argentina.svg.png",
    overall: 94,
    potential: 94,
    position: "Forward",
    value: 150000000,
    wage: 750000,
    preferred_foot: "Left",
    work_rate: "Medium/High",
    body_type: "Lean",
    international_reputation: "5",
    skill_moves: "4",
    weak_foot: "4",
    height: 170,
    weight: 72,
  },
  {
    id: "2",
    name: "Cristiano Ronaldo",
    age: "36",
    photo: "https://i.pravatar.cc/150?u=cristiano-ronaldo",
    nationality: "Portugal",
    flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Flag_of_Portugal.svg/1280px-Flag_of_Portugal.svg.png",
    overall: 92,
    potential: 92,
    position: "Forward",
    value: 120000000,
    wage: 800000,
    preferred_foot: "Right",
    work_rate: "High/High",
    body_type: "Athletic",
    international_reputation: "5",
    skill_moves: "5",
    weak_foot: "4",
    height: 187,
    weight: 83,
  },
  {
    id: "3",
    name: "Neymar Jr",
    age: "29",
    photo: "https://i.pravatar.cc/150?u=neymar-jr",
    nationality: "Brazil",
    flag: "https://upload.wikimedia.org/wikipedia/en/thumb/0/05/Flag_of_Brazil.svg/1280px-Flag_of_Brazil.svg.png",
    overall: 91,
    potential: 92,
    position: "Forward",
    value: 110000000,
    wage: 600000,
    preferred_foot: "Right",
    work_rate: "High/Medium",
    body_type: "Lean",
    international_reputation: "5",
    skill_moves: "5",
    weak_foot: "5",
    height: 175,
    weight: 68,
  },
  {
    id: "4",
    name: "Kevin De Bruyne",
    age: "30",
    photo: "https://i.pravatar.cc/150?u=kevin-de-bruyne",
    nationality: "Belgium",
    flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Flag_of_Belgium.svg/1280px-Flag_of_Belgium.svg.png",
    overall: 91,
    potential: 91,
    position: "Midfielder",
    value: 120000000,
    wage: 600000,
    preferred_foot: "Right",
    work_rate: "High/High",
    body_type: "Normal",
    international_reputation: "4",
    skill_moves: "4",
    weak_foot: "5",
    height: 181,
    weight: 68,
  },
  {
    id: "5",
    name: "Robert Lewandowski",
    age: "33",
    photo: "https://i.pravatar.cc/150?u=robert-lewandowski",
    nationality: "Poland",
    flag:  "https://upload.wikimedia.org/wikipedia/en/thumb/1/12/Flag_of_Poland.svg/1280px-Flag_of_Poland.svg.png",
    overall: 92,
    potential: 92,
    position: "Forward",
    value: 100000000,
    wage: 550000,
    preferred_foot: "Right",
    work_rate: "High/High",
    body_type: "Stocky",
    international_reputation: "4",
    skill_moves: "4",
    weak_foot: "4",
    height: 184,
    weight: 80,
  },
  {
    id: "6",
    name: "Virgil van Dijk",
    age: "30",
    photo: "https://i.pravatar.cc/150?u=virgil-van-dijk",
    nationality: "Netherlands",
    flag:"https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Flag_of_the_Netherlands.svg/1280px-Flag_of_the_Netherlands.svg.png",
    overall: 90,
    potential: 90,
    position: "Defender",
    value: 80000000,
    wage: 500000,
    preferred_foot: "Right",
    work_rate: "Medium/High",
    body_type: "Normal",
    international_reputation: "4",
    skill_moves: "2",
    weak_foot: "3",
    height: 193,
    weight: 92,
  },
  {
    id: "7",
    name: "Mohamed Salah",
    age: "29",
    photo: "https://i.pravatar.cc/150?u=mohamed-salah",
    nationality: "Egypt",
    flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Flag_of_Egypt.svg/1280px-Flag_of_Egypt.svg.png",
    overall: 90,
    potential: 90,
    position: "Forward",
    value: 100000000,
    wage: 550000,
    preferred_foot: "Left",
    work_rate: "High/Medium",
    body_type: "Lean",
    international_reputation: "4",
    skill_moves: "4",
    weak_foot: "3",
    height: 175,
    weight: 71,
  },
  {
    id: "8",
    name: "Kylian Mbappe",
    age: "23",
    photo: "https://i.pravatar.cc/150?u=kylian-mbappe",
    nationality: "France",
    flag:"https://upload.wikimedia.org/wikipedia/en/thumb/c/c3/Flag_of_France.svg/1280px-Flag_of_France.svg.png",
    overall: 91,
    potential: 95,
    position: "Forward",
    value: 130000000,
    wage: 700000,
    preferred_foot: "Right",
    work_rate: "High/Low",
    body_type: "Lean",
    international_reputation: "5",
    skill_moves: "5",
    weak_foot: "4",
    height: 178,
    weight: 73,
  },
  {
    id: "9",
    name: "Bruno Fernandes",
    age: "27",
    photo: "https://i.pravatar.cc/150?u=bruno-fernandes",
    nationality: "Portugal",
    flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Flag_of_Portugal.svg/1280px-Flag_of_Portugal.svg.png",
    overall: 88,
    potential: 90,
    position: "Midfielder",
    value: 90000000,
    wage: 500000,
    preferred_foot: "Right",
    work_rate: "High/High",
    body_type: "Normal",
    international_reputation: "4",
    skill_moves: "4",
    weak_foot: "4",
    height: 179,
    weight: 69,
  },
  {
    id: "10",
    name: "Sergio Ramos",
    age: "35",
    photo: "https://i.pravatar.cc/150?u=sergio-ramos",
    nationality: "Spain",
    flag:  "https://upload.wikimedia.org/wikipedia/en/thumb/9/9a/Flag_of_Spain.svg/1280px-Flag_of_Spain.svg.png",
    overall: 88,
    potential: 88,
    position: "Defender",
    value: 60000000,
    wage: 450000,
    preferred_foot: "Right",
    work_rate: "Medium/High",
    body_type: "Stocky",
    international_reputation: "5",
    skill_moves: "3",
    weak_foot: "3",
    height: 184,
    weight: 82,
  },
  {
    id: "11",
    name: "Alphonso Davies",
    age: "21",
    photo: "https://i.pravatar.cc/150?u=alphonso-davies",
    nationality: "Canada",
    flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Flag_of_Canada_%28Pantone%29.svg/1280px-Flag_of_Canada_%28Pantone%29.svg.png",
    overall: 86,
    potential: 92,
    position: "Defender",
    value: 75000000,
    wage: 350000,
    preferred_foot: "Left",
    work_rate: "High/High",
    body_type: "Lean",
    international_reputation: "4",
    skill_moves: "4",
    weak_foot: "3",
    height: 183,
    weight: 72,
  },
  {
    id: "12",
    name: "Erling Haaland",
    age: "21",
    photo: "https://i.pravatar.cc/150?u=erling-haaland",
    nationality: "Norway",
    flag:"https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Flag_of_Norway.svg/1280px-Flag_of_Norway.svg.png",
    overall: 87,
    potential: 92,
    position: "Forward",
    value: 90000000,
    wage: 400000,
    preferred_foot: "Right",
    work_rate: "High/Low",
    body_type: "Lean",
    international_reputation: "4",
    skill_moves: "3",
    weak_foot: "4",
    height: 194,
    weight: 87,
  },
  // Add more players as needed
];
